name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Setup wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      - name: Build rustboyadvance-wasm
        run: |
          wasm-pack build platform/rustboyadvance-wasm  --release -- --features "wee_alloc"

      - name: Build WebApp
        run: |
          cd ./platform/rustboyadvance-wasm/app
          npm install
          npm run build

      - name: "Deploy 🚀"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.ACCESS_TOKEN }}'
          publish_branch: gh-pages
          publish_dir: ./platform/rustboyadvance-wasm/app/dist
          keep_files: false
