[package]
name = "rustboyadvance-minifb"
version = "0.1.0"
authors = ["Michel Heily <michelheily@gmail.com>"]
edition = "2018"

[dependencies]
rustboyadvance-core = {path = "../../core/"}
minifb = "0.11.2"
clap = {version = "2.33", features = ["color", "yaml"]}
bit = "^0.1"
