#include "_matmul_matmuladdfusion_fused_weights.h"
#include "_matmul_matmuladdfusion_fused_biases.h"
#include "forward.h"
#define  _MATMUL_MATMULADDFUSION_FUSED_INPUT_IDX 0
#define  _MATMUL_MATMULADDFUSION_FUSED_OUTPUT_IDX 10
#define _MATMUL_MATMULADDFUSION_FUSED_IN_SIZE 10
#define _MATMUL_MATMULADDFUSION_FUSED_OUT_SIZE 5
#define _MATMUL_MATMULADDFUSION_FUSED_MULTIPLIER 2970738
#define _MATMUL_MATMULADDFUSION_FUSED_SHIFT 30

int8_t mem_buffer[15];

void forward(int8_t *input,int8_t *output) {
    qgemm_int8_t(input, output, _MATMUL_MATMULADDFUSION_FUSED_weights, _MATMUL_MATMULADDFUSION_FUSED_biases, _MATMUL_MATMULADDFUSION_FUSED_IN_SIZE, _MATMUL_MATMULADDFUSION_FUSED_OUT_SIZE, _MATMUL_MATMULADDFUSION_FUSED_MULTIPLIER, _MATMUL_MATMULADDFUSION_FUSED_SHIFT);
}