name: Docker Build and Push 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch: # allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # needed to push to GHCR
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/pkmnrlarena/ci-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version' pyproject.toml | head -n1 | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Package version: $VERSION"

      - name: Build Docker image
        run: |
          echo "Building $IMAGE:latest and $IMAGE:$VERSION"
          docker build -t $IMAGE:latest -t $IMAGE:$VERSION .

      - name: Push Docker images
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:$VERSION

